=== Aiweline/WelineFramework/app/code/Weline/Framework/Event/etc/xsd/events.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
* 文件信息
* 作者：邹万才
* 网名：秋枫雁飞(可以百度看看)
* 网站：www.aiweline.com/bbs.aiweline.com
* 工具：PhpStorm
* 日期：2021/2/1
* 时间：18:04
* 版权：Copyright (c) 2021 AIWELINE (http://www.aiweline.com)
* 描述：此文件源码由Aiweline（秋枫雁飞）开发，请勿随意修改源码！
*/
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="urn:Weline_Framework::Event/etc/xsd/event.xsd"
           elementFormDefault="qualified"
           version="1.0">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="event" type="eventDeclaration" minOccurs="0" maxOccurs="unbounded">
                    <xs:unique name="uniqueObserverName">
                        <xs:annotation>
                            <xs:documentation>
                                观察者名称必须唯一。
                            </xs:documentation>
                        </xs:annotation>
                        <xs:selector xpath="observer"/>
                        <xs:field xpath="@name"/>
                    </xs:unique>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueEventName">
            <xs:annotation>
                <xs:documentation>
                    事件名称必须唯一。
                </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="event"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="eventDeclaration">
        <xs:annotation>
            <xs:documentation>
                事件声明。
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="observer" type="observerDeclaration" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="eventName" use="required"/>
    </xs:complexType>

    <xs:complexType name="observerDeclaration">
        <xs:annotation>
            <xs:documentation>
                观察者声明。
            </xs:documentation>
        </xs:annotation>
        <xs:attribute name="name" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>
                    观察者名称，必须唯一。
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="instance" type="xs:string" use="optional">
            <xs:annotation>
                <xs:documentation>
                    实现观察者方法的类名。
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="disabled" type="xs:boolean" use="optional">
            <xs:annotation>
                <xs:documentation>
                    是否禁用该观察者。
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="shared" type="xs:boolean" use="optional">
            <xs:annotation>
                <xs:documentation>
                    是否共享观察者实例。
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="sort" type="xs:string" use="optional">
            <xs:annotation>
                <xs:documentation>
                    观察者的排序顺序。数值越小越先执行。
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:simpleType name="eventName">
        <xs:annotation>
            <xs:documentation>
                事件名称只能包含 [a-zA-Z0-9_]。
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9_]+"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Aiweline/WelineFramework/app/code/Weline/Database/etc/events.xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:weline:framework:etc/events.xsd">
    <!-- 模块升级事件监听 -->
    <event name="module_upgrade_after">
        <observer name="weline_database_module_upgrade" instance="Weline\Database\Observer\ModuleUpgradeObserver" />
    </event>
    
    <!-- 系统升级事件监听 -->
    <event name="setup_upgrade_after">
        <observer name="weline_database_setup_upgrade" instance="Weline\Database\Observer\SetupUpgradeObserver" />
    </event>
    
    <!-- 模块安装事件监听 -->
    <event name="module_install_after">
        <observer name="weline_database_module_install" instance="Weline\Database\Observer\ModuleUpgradeObserver" />
    </event>
    
    <!-- 模块卸载事件监听 -->
    <event name="module_uninstall_after">
        <observer name="weline_database_module_uninstall" instance="Weline\Database\Observer\ModuleUpgradeObserver" />
    </event>
</config>
